# The URL the site will be built for
base_url = "https://khb7840.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "Hyunbin Kim"
description = "Somewhere between bioinformatician and genomic researcher. Daydreaming coffee addict."

taxonomies = [
    { name = "categories" },
    { name = "tags" },
]

[markdown]

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "agola-dark"

[extra]
# Put all your custom variables here

links = [
    { title = "Mail", href = "mailto:khb7840@gmail.com" },
    { title = "GitHub", href = "https://github.com/khb7840" },
    { title = "Twitter", href = "https://x.com/hkgenomics" },
    # { title = "Bluesky", href = "https://bsky.app/profile/hbkgenomics.bsky.social" }
    # { title = "LinkedIn", href = "https://linkedin.com" }
]
